version: 0.2

env:
  variables:
    ImageName: simple-docker-service

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 963108901187.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - ls -la  # Debug: List files to confirm Dockerfile exists
      - docker build -t $ImageName -f ./Dockerfile .
  post_build:
    commands:
      - echo Tagging the image...
      - docker tag $ImageName:latest 963108901187.dkr.ecr.us-east-2.amazonaws.com/$ImageName:latest
      - echo Pushing the Docker image to ECR...
      - docker push 963108901187.dkr.ecr.us-east-2.amazonaws.com/$ImageName:latest

artifacts:
  files: []

