version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 963108901187.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - cd repo                 # <--- add this line to go into /root/myapp/repo
      - docker build -t $ImageName -f Dockerfile .
  post_build:
    commands:
      - docker tag $ImageName:latest 963108901187.dkr.ecr.us-east-2.amazonaws.com/$ImageName:latest
      - docker push 963108901187.dkr.ecr.us-east-2.amazonaws.com/$ImageName:latest

